name: flutter_sandbox

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.4
      flutter: ^3.24.5
    dependencies:
      flutter:
        sdk: flutter
    dev_dependencies:
      build_runner: ^2.4.12
      flutter_test:
        sdk: flutter
ide:
  intellij:
    enabled: false
