name: flutter_sandbox

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.4
      flutter: ^3.24.5
    dependencies:
      flutter:
        sdk: flutter
      flutter_riverpod: ^2.6.1
      riverpod_annotation: ^2.6.1
    dev_dependencies:
      build_runner: ^2.4.12
      custom_lint: ^0.7.0
      flutter_test:
        sdk: flutter
      riverpod_generator: ^2.6.1
      riverpod_lint: ^2.6.1

scripts:
  lint:
    run: dart run custom_lint
    exec:
      concurrency: 5
    packageFilters:
      dependsOn: custom_lint
  rebuild:
    run: dart run build_runner build -d && melos format -c 5
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

ide:
  intellij:
    enabled: false
