name: feature_flutter_gen_sample
description: "FlutterGen sample UI package"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

flutter_gen:
  assets:
      outputs:
        package_parameter_enabled: true
flutter:
  uses-material-design: true
  assets:
    - assets/
