name: feature_counter
description: "Counter UI package"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  app_core_app:
    path: ../../core/app

  app_core_common:
    path: ../../core/common

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
