name: app_core_common
description: "Counter UI package"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  test: ^1.25.0
