name: flutter_sandbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  app_core_common:
    path: ../packages/core/common

  app_core_app:
    path: ../packages/core/app

  feature_counter:
    path: ../packages/features/counter
  
  feature_textform:
    path: ../packages/features/textform

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
