name: flutter_sandbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  app_core_app:
    path: ../packages/core/app

  app_core_common:
    path: ../packages/core/common

  app_repositories:
    path: ../packages/core/repositories

  cupertino_icons: ^1.0.8

  feature_counter:
    path: ../packages/features/counter

  feature_flutter_gen_sample:
    path: ../packages/features/flutter_gen_sample
    
  feature_local_asset:
    path: ../packages/features/local_asset

  feature_rss:
    path: ../packages/features/rss

  feature_textform:
    path: ../packages/features/textform

  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
