name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04

    timeout-minutes: 5

    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: ".github/labeler.yaml"
          sync-labels: true
